### ISSUE TITLE
我在jni调用toast.show如何调用

### ISSUE THREAD

**Issue by netstu** [richardchien/natiflect#1]
natiflect::Class toastclz(env, "android/widget/Toast");
    jobject toastobj = (jobject)toastclz.CallStatic_L("makeText", "(Landroid/content/Context;Ljava/lang/CharSequence;I)Landroid/widget/Toast;", jobj, "aaa", 1);

    natiflect::Object<jobject>(env, toastobj).Call_V("show", "()V");

**Comment by stdrc** [comment]
你试试把要 toast 的字符串先创建一个 `jstring` 再传入

**Comment by netstu** [comment]
@richardchien 是的，我已经试好了，直接双引号的字符串的确会造成问题，谢谢你了
